AllCops:
  NewCops: enable

Bundler/DuplicatedGem:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Style/FrozenStringLiteralComment:
  Enabled: false
