require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Bundler/DuplicatedGem:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

RSpec/DescribeClass:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: 'compact'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false
