name: Ruby

on: [push]

jobs:
  build:
    env:
      PUPPET_GEM_VERSION: "~> 6.10.0"
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.5
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake spec

  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v3.2.0
      with:
        fail_level: 'fatal'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  superlint:
    runs-on: ubuntu-18.04
    steps:
    - name: SuperLint Code Base
      uses: docker://github/super-linter:v3
      env:
        VALIDATE_ALL_CODEBASE: true
        DISABLE_ERRORS: true
